/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.funcoes.Mensagens;
import br.edu.utfpr.entidades.Produtos;

/**
 *
 * @author ferlo
 */
public class CadastroDeProdutos extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroDeProdutos
     */
    public CadastroDeProdutos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneProdutos = new javax.swing.JTabbedPane();
        jPanelAdicionarProdutoAba1 = new javax.swing.JPanel();
        jButtonFecharAba1 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelProduto = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jLabelQuantidadeVolume = new javax.swing.JLabel();
        jLabelUnidadeMedida = new javax.swing.JLabel();
        jTextFieldProduto = new javax.swing.JTextField();
        jTextFieldCategoria = new javax.swing.JTextField();
        jTextFieldUnidadeMedida = new javax.swing.JTextField();
        jLabelValor = new javax.swing.JLabel();
        jFormattedTextFieldQuantidadeVolume = new javax.swing.JFormattedTextField();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jPanelProdutosCadastradosAba2 = new javax.swing.JPanel();
        jButtonFecharAba2 = new javax.swing.JButton();
        jScrollPaneProdutos = new javax.swing.JScrollPane();
        jTableProdutos = new javax.swing.JTable();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jLabelProdutoPesquisa = new javax.swing.JLabel();
        jTextFieldProdutoPesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Produtos");

        jButtonFecharAba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/fechar.png"))); // NOI18N
        jButtonFecharAba1.setText("Fechar");
        jButtonFecharAba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAba1ActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelProduto.setText("Produto *");

        jLabelCategoria.setText("Categoria *");

        jLabelQuantidadeVolume.setText("Quantidade/Volume *");

        jLabelUnidadeMedida.setText("Unidade de Medida *");

        jLabelValor.setText("Valor *");

        jFormattedTextFieldQuantidadeVolume.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        javax.swing.GroupLayout jPanelAdicionarProdutoAba1Layout = new javax.swing.GroupLayout(jPanelAdicionarProdutoAba1);
        jPanelAdicionarProdutoAba1.setLayout(jPanelAdicionarProdutoAba1Layout);
        jPanelAdicionarProdutoAba1Layout.setHorizontalGroup(
            jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                        .addComponent(jLabelCategoria)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCategoria))
                    .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                        .addComponent(jLabelProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProduto))
                    .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                        .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                                .addComponent(jLabelValor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldValor))
                            .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                                .addComponent(jLabelQuantidadeVolume)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldQuantidadeVolume, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                                .addGap(0, 27, Short.MAX_VALUE)
                                .addComponent(jButtonFecharAba1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar))
                            .addGroup(jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                                .addComponent(jLabelUnidadeMedida)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldUnidadeMedida)))))
                .addContainerGap())
        );
        jPanelAdicionarProdutoAba1Layout.setVerticalGroup(
            jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAdicionarProdutoAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduto)
                    .addComponent(jTextFieldProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCategoria)
                    .addComponent(jTextFieldCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQuantidadeVolume)
                    .addComponent(jLabelUnidadeMedida)
                    .addComponent(jTextFieldUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldQuantidadeVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValor)
                    .addComponent(jFormattedTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanelAdicionarProdutoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonFecharAba1))
                .addContainerGap())
        );

        jTabbedPaneProdutos.addTab("Adicionar Produto", jPanelAdicionarProdutoAba1);

        jButtonFecharAba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/fechar.png"))); // NOI18N
        jButtonFecharAba2.setText("Fechar");
        jButtonFecharAba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAba2ActionPerformed(evt);
            }
        });

        jTableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produtos", "Categoria", "Quantidade/Volume ", "Unidade de Medida", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneProdutos.setViewportView(jTableProdutos);

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");

        jLabelProdutoPesquisa.setText("Produto");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setText("Perquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelProdutosCadastradosAba2Layout = new javax.swing.GroupLayout(jPanelProdutosCadastradosAba2);
        jPanelProdutosCadastradosAba2.setLayout(jPanelProdutosCadastradosAba2Layout);
        jPanelProdutosCadastradosAba2Layout.setHorizontalGroup(
            jPanelProdutosCadastradosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProdutosCadastradosAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutosCadastradosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutosCadastradosAba2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFecharAba2))
                    .addComponent(jScrollPaneProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                    .addGroup(jPanelProdutosCadastradosAba2Layout.createSequentialGroup()
                        .addComponent(jLabelProdutoPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldProdutoPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar)))
                .addContainerGap())
        );
        jPanelProdutosCadastradosAba2Layout.setVerticalGroup(
            jPanelProdutosCadastradosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProdutosCadastradosAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelProdutosCadastradosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProdutoPesquisa)
                    .addComponent(jTextFieldProdutoPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProdutosCadastradosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonFecharAba2)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir))
                .addContainerGap())
        );

        jTabbedPaneProdutos.addTab("Produtos Cadastrados", jPanelProdutosCadastradosAba2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProdutos)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProdutos)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharAba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAba1ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButtonFecharAba1ActionPerformed

    private void jButtonFecharAba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAba2ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButtonFecharAba2ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (validaCampos()) {
            Produtos produtos = new Produtos(
                jTextFieldProduto.getText(),
                jTextFieldCategoria.getText(),
                Float.parseFloat(jFormattedTextFieldQuantidadeVolume.getText().toString().replace(".", "").replace(",", ".")),
                jTextFieldUnidadeMedida.getText(),
                Float.parseFloat(jFormattedTextFieldValor.getText().toString().replace(".", "").replace(",", "."))
            );
            
            produtos.salvar();
            limpaCampos();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void limpaCampos() {
        jTextFieldProduto.setText("");
        jTextFieldCategoria.setText("");
        jFormattedTextFieldQuantidadeVolume.setText("");
        jTextFieldUnidadeMedida.setText("");
        jFormattedTextFieldValor.setText("");
    }
    
    private boolean validaCampos() {
        Mensagens mensagens = new Mensagens();
        
        if (jTextFieldProduto.getText().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Produto");
            jTextFieldProduto.requestFocus();
            return false;
        } else if (jTextFieldCategoria.getText().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Categoria");
            jTextFieldCategoria.requestFocus();
            return false;
        } else if (jFormattedTextFieldQuantidadeVolume.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Quantidade/Volume");
            jFormattedTextFieldQuantidadeVolume.requestFocus();
            return false;
        } else if (jFormattedTextFieldQuantidadeVolume.getText().toString().equals("0")) {
            mensagens.errorMessage("Campo Inválido", "Preencha uma Quantidade/Volume maior que 0");
            jFormattedTextFieldQuantidadeVolume.requestFocus();
            return false;
        }  else if (jTextFieldUnidadeMedida.getText().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Unidade de Medida");
            jTextFieldUnidadeMedida.requestFocus();
            return false;
        } else if (jFormattedTextFieldValor.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Valor");
            jFormattedTextFieldValor.requestFocus();
            return false;
        } else if (jFormattedTextFieldValor.getText().toString().equals("0,00")) {
            mensagens.errorMessage("Campo Inválido", "Preencha um Valor maior que 0");
            jFormattedTextFieldValor.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharAba1;
    private javax.swing.JButton jButtonFecharAba2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidadeVolume;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelProduto;
    private javax.swing.JLabel jLabelProdutoPesquisa;
    private javax.swing.JLabel jLabelQuantidadeVolume;
    private javax.swing.JLabel jLabelUnidadeMedida;
    private javax.swing.JLabel jLabelValor;
    private javax.swing.JPanel jPanelAdicionarProdutoAba1;
    private javax.swing.JPanel jPanelProdutosCadastradosAba2;
    private javax.swing.JScrollPane jScrollPaneProdutos;
    private javax.swing.JTabbedPane jTabbedPaneProdutos;
    private javax.swing.JTable jTableProdutos;
    private javax.swing.JTextField jTextFieldCategoria;
    private javax.swing.JTextField jTextFieldProduto;
    private javax.swing.JTextField jTextFieldProdutoPesquisar;
    private javax.swing.JTextField jTextFieldUnidadeMedida;
    // End of variables declaration//GEN-END:variables
}
