/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.DAO.EntradaLotesDao;
import br.edu.utfpr.DAO.PerdasDao;
import br.edu.utfpr.entidades.EntradaLotes;
import br.edu.utfpr.entidades.Perdas;
import br.edu.utfpr.funcoes.Mensagens;
import br.edu.utfpr.model.EntradaDeLotesListModel;
import br.edu.utfpr.model.PerdasListModel;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ferlo
 */
public class EditarPerdas extends javax.swing.JInternalFrame {
    // Guarda os codigos dos lotes do combobox
    Integer[] codigosLotes;
    
    // Conexão com banco
    EntradaLotesDao entradaLotesDao = new EntradaLotesDao();
    EntradaDeLotesListModel entradaLotesListModel;
    
    // Conexão com banco
    PerdasDao perdasDao = new PerdasDao();
    PerdasListModel perdasListModel;
    List<Perdas> ListaPerdas;
    
    int idPerda;
    
    // Funcoes para mensagens
    Mensagens mensagens = new Mensagens();
    
    RegistroDePerdas registroDePerdas;
    
    public EditarPerdas(List<Perdas> ListaPerdas, RegistroDePerdas registroDePerdas) {
        initComponents();
        this.ListaPerdas = ListaPerdas;
        this.registroDePerdas = registroDePerdas;
        alimentaComboBoxLotes();
        alimentaCampos();
    }
    
    private void alimentaComboBoxLotes() {
        
        List<EntradaLotes> listaEntradaLotes = entradaLotesDao.listar();
        entradaLotesListModel = new EntradaDeLotesListModel(listaEntradaLotes);
        
        // Cria um array com os itens para a ComboBox
        String[] nomesLotes = new String[entradaLotesListModel.getRowCount()+1];
        
        codigosLotes = new Integer[entradaLotesListModel.getRowCount()];
        
        for (int i=0; i<=entradaLotesListModel.getRowCount(); i++) {
            if (i==0) {
                nomesLotes[i] = "Selecione o Lote";
            } else {
                nomesLotes[i] = entradaLotesListModel.getValueAt(i-1, 1).toString();
                codigosLotes[i-1] = Integer.parseInt(entradaLotesListModel.getValueAt(i-1, 0).toString());
            }
        }
        
        // Cria um modelo de dados para a ComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(nomesLotes);

        // Define o modelo de dados
        jComboBoxLotes.setModel(model);
    }

    public void alimentaCampos() {
        perdasListModel = new PerdasListModel(ListaPerdas);
        
        idPerda = Integer.parseInt(perdasListModel.getValueAt(0, 0).toString());
        jComboBoxLotes.setSelectedIndex(indexComboBoxLotePeloCodigo(perdasDao.codLotePeloCodPerda(idPerda)));
        jTextFieldDescricaoMotivo.setText(perdasListModel.getValueAt(0, 2).toString());
        jFormattedTextFieldContagemPerdas.setText(perdasListModel.getValueAt(0, 3).toString());
        jFormattedTextFieldDataContagem.setText(perdasListModel.getValueAt(0, 4).toString());
    }
    
    private int indexComboBoxLotePeloCodigo(int codigo) {
        int index = 0;
        for (int i=0; i<codigosLotes.length; i++) {
            if (codigosLotes[i] == codigo) {
                index = i+1;
            }
        }
        return index;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextFieldDataContagem = new javax.swing.JFormattedTextField();
        jComboBoxLotes = new javax.swing.JComboBox<>();
        jLabelLote = new javax.swing.JLabel();
        jLabelDescricaoMotivo = new javax.swing.JLabel();
        jTextFieldDescricaoMotivo = new javax.swing.JTextField();
        jLabelContagemPerdas = new javax.swing.JLabel();
        jFormattedTextFieldContagemPerdas = new javax.swing.JFormattedTextField();
        jButtonFecharAba1 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelDataContagem = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Perdas");

        jFormattedTextFieldDataContagem.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jComboBoxLotes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um Lote", "Lote Teste" }));

        jLabelLote.setText("Lote * ");

        jLabelDescricaoMotivo.setText("Descrição/Motivo *");

        jLabelContagemPerdas.setText("Contagem de Perdas *");

        jFormattedTextFieldContagemPerdas.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        jButtonFecharAba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/fechar.png"))); // NOI18N
        jButtonFecharAba1.setText("Fechar");
        jButtonFecharAba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAba1ActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelDataContagem.setText("Data da Contagem *");
        jLabelDataContagem.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelLote)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxLotes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 191, Short.MAX_VALUE)
                        .addComponent(jButtonFecharAba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDescricaoMotivo)
                            .addComponent(jLabelContagemPerdas)
                            .addComponent(jLabelDataContagem))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldDescricaoMotivo)
                            .addComponent(jFormattedTextFieldContagemPerdas)
                            .addComponent(jFormattedTextFieldDataContagem))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLote)
                    .addComponent(jComboBoxLotes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDescricaoMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDescricaoMotivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelContagemPerdas)
                    .addComponent(jFormattedTextFieldContagemPerdas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataContagem)
                    .addComponent(jFormattedTextFieldDataContagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonFecharAba1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharAba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAba1ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButtonFecharAba1ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (validaCampos()) {
            Perdas perdas = new Perdas(
                codigosLotes[jComboBoxLotes.getSelectedIndex()-1],
                jComboBoxLotes.getSelectedItem().toString(),
                jTextFieldDescricaoMotivo.getText(),
                Integer.parseInt(jFormattedTextFieldContagemPerdas.getText().toString().replace(".", "")),
                jFormattedTextFieldDataContagem.getText().toString()
            );
            
            perdas.setIdRegistroPerdas(idPerda);
            
            // Gravação no banco
            perdasDao.alterar(perdas);
                    
            listagemDeDados("");
            
            super.dispose();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private boolean validaCampos() {
        if (jComboBoxLotes.getSelectedIndex() == 0) {
            mensagens.errorMessage("Campo Inválido","Selecione um Lote");
            jComboBoxLotes.requestFocus();
            return false;
        } else if (perdasDao.verificaLotesBaixado(codigosLotes[jComboBoxLotes.getSelectedIndex()-1])) {
            mensagens.errorMessage("Campo Inválido","Selecione um Lote que já não foi baixado");
            jComboBoxLotes.requestFocus();
            return false;
        } else if (jTextFieldDescricaoMotivo.getText().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Descrição/Motivo");
            jTextFieldDescricaoMotivo.requestFocus();
            return false;
        } else if (jFormattedTextFieldContagemPerdas.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido", "Preencha o campo Preencha o campo Contagem de Perdas");
            jFormattedTextFieldContagemPerdas.requestFocus();
            return false;
        } else if (jFormattedTextFieldContagemPerdas.getText().toString().equals("0")) {
            mensagens.errorMessage("Campo Inválido", "Preencha uma Contagem de Perdas maior que 0");
            jFormattedTextFieldContagemPerdas.requestFocus();
            return false;
        } else if (validaQuantidadeDePerdasDoLote(codigosLotes[jComboBoxLotes.getSelectedIndex()-1])) {
            mensagens.errorMessage("Campo Inválido", "Contagem de perdas de frangos excedidendo a contagem da entrada");
            jFormattedTextFieldContagemPerdas.requestFocus();
            return false;
        } else if (jFormattedTextFieldDataContagem.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Data da Contagem");
            jFormattedTextFieldDataContagem.requestFocus();
            return false;
        } else {
            return true;
        }
    }
    
    private boolean validaQuantidadeDePerdasDoLote(int codigoLote) {
        // Variavel para soma inicialida com o valor do campo de perdas
        int somaQuantidadeDePerdasDoLote = Integer.parseInt(jFormattedTextFieldContagemPerdas.getText().toString().replace(".", ""));
        
        // Variavel alimentada com o valor total de entrada de frangos no lote
        int quantidadeDeFrangosNaEntradaDoLote = perdasDao.buscaQuantidadeDeFrangosDoLote(codigoLote);
        
        List<Perdas> lista = perdasDao.buscarPorCodigoDoLote(codigoLote);
        perdasListModel = new PerdasListModel(lista);
        
        for (int i=0; i<perdasListModel.getRowCount(); i++) {
            somaQuantidadeDePerdasDoLote = somaQuantidadeDePerdasDoLote+Integer.parseInt(perdasListModel.getValueAt(i, 3).toString());
        }
        
        return somaQuantidadeDePerdasDoLote>quantidadeDeFrangosNaEntradaDoLote;
    }
    
    private void listagemDeDados(String nome) {
        registroDePerdas.listagemDeDados(nome);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFecharAba1;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxLotes;
    private javax.swing.JFormattedTextField jFormattedTextFieldContagemPerdas;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataContagem;
    private javax.swing.JLabel jLabelContagemPerdas;
    private javax.swing.JLabel jLabelDataContagem;
    private javax.swing.JLabel jLabelDescricaoMotivo;
    private javax.swing.JLabel jLabelLote;
    private javax.swing.JTextField jTextFieldDescricaoMotivo;
    // End of variables declaration//GEN-END:variables
}
