/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.edu.utfpr.view;

import br.edu.utfpr.DAO.EntradaLotesDao;
import br.edu.utfpr.DAO.GranjasDao;
import br.edu.utfpr.entidades.EntradaLotes;
import br.edu.utfpr.entidades.Granjas;
import br.edu.utfpr.funcoes.Mensagens;
import br.edu.utfpr.model.EntradaDeLotesListModel;
import br.edu.utfpr.model.GranjasListModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author ferlo
 */
public class EntradaDeLotes extends javax.swing.JInternalFrame {
    // Guarda os codigos das granjas do combobox
    Integer[] codigosGranjas;
    
    // Guarda as quantidades de frangos das granjas do combobox
    Integer[] quantidadesFrangosGranjas;
    
    // Conexão com banco
    GranjasDao granjasDao = new GranjasDao();
    GranjasListModel granjasListModel;
    
    // Conexão com banco
    EntradaLotesDao entradaLotesDao = new EntradaLotesDao();
    EntradaDeLotesListModel entradaLotesListModel;
    
    public EntradaDeLotes() {
        initComponents();
        
        // Listagem na tabela
        List<EntradaLotes> lista = entradaLotesDao.listar();
        entradaLotesListModel = new EntradaDeLotesListModel(lista);
        jTableEntradaLote.setModel(entradaLotesListModel);
        
        alimentaComboBoxGranjas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPaneEntradaLotes = new javax.swing.JTabbedPane();
        jPanelRegistrarEntradaLoteAba1 = new javax.swing.JPanel();
        jButtonFecharAba1 = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jLabelIdentificador = new javax.swing.JLabel();
        jLabelQuantidadeFrangos = new javax.swing.JLabel();
        jTextFieldIdentificador = new javax.swing.JTextField();
        jComboBoxGranjas = new javax.swing.JComboBox<>();
        jFormattedTextFieldQuantidadeFrangos = new javax.swing.JFormattedTextField();
        jLabelGranja = new javax.swing.JLabel();
        jLabelValorEntrada = new javax.swing.JLabel();
        jFormattedTextFieldValorEntrada = new javax.swing.JFormattedTextField();
        jLabelDataEntrada = new javax.swing.JLabel();
        jFormattedTextFieldDataEntrada = new javax.swing.JFormattedTextField();
        jPanelLotesAlojadosAba2 = new javax.swing.JPanel();
        jButtonFecharAba2 = new javax.swing.JButton();
        jScrollPaneEntradaLote = new javax.swing.JScrollPane();
        jTableEntradaLote = new javax.swing.JTable();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelIdentificadorLotePesquisa = new javax.swing.JLabel();
        jTextFieldIdentificadorLotePesquisar = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Entrada de Lotes");

        jButtonFecharAba1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/fechar.png"))); // NOI18N
        jButtonFecharAba1.setText("Fechar");
        jButtonFecharAba1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAba1ActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jLabelIdentificador.setText("Identificador *");

        jLabelQuantidadeFrangos.setText("Quantidade de Frangos *");

        jComboBoxGranjas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione a Granja", "Granja Teste" }));

        jFormattedTextFieldQuantidadeFrangos.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0"))));

        jLabelGranja.setText("Granja *");

        jLabelValorEntrada.setText("Valor de Entrada do Lote *");

        jFormattedTextFieldValorEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        jLabelDataEntrada.setText("Data da Entrada *");

        jFormattedTextFieldDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout jPanelRegistrarEntradaLoteAba1Layout = new javax.swing.GroupLayout(jPanelRegistrarEntradaLoteAba1);
        jPanelRegistrarEntradaLoteAba1.setLayout(jPanelRegistrarEntradaLoteAba1Layout);
        jPanelRegistrarEntradaLoteAba1Layout.setHorizontalGroup(
            jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonFecharAba1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar))
                    .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                        .addComponent(jLabelIdentificador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdentificador))
                    .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                        .addComponent(jLabelGranja)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxGranjas, 0, 411, Short.MAX_VALUE))
                    .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                        .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelQuantidadeFrangos)
                            .addComponent(jLabelValorEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jFormattedTextFieldValorEntrada)
                            .addComponent(jFormattedTextFieldQuantidadeFrangos)))
                    .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                        .addComponent(jLabelDataEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFormattedTextFieldDataEntrada)))
                .addContainerGap())
        );
        jPanelRegistrarEntradaLoteAba1Layout.setVerticalGroup(
            jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegistrarEntradaLoteAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificador)
                    .addComponent(jTextFieldIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxGranjas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelGranja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextFieldQuantidadeFrangos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelQuantidadeFrangos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelValorEntrada)
                    .addComponent(jFormattedTextFieldValorEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataEntrada)
                    .addComponent(jFormattedTextFieldDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanelRegistrarEntradaLoteAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonFecharAba1))
                .addContainerGap())
        );

        jTabbedPaneEntradaLotes.addTab("Registrar Entrada de Lote", jPanelRegistrarEntradaLoteAba1);

        jButtonFecharAba2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/fechar.png"))); // NOI18N
        jButtonFecharAba2.setText("Fechar");
        jButtonFecharAba2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharAba2ActionPerformed(evt);
            }
        });

        jTableEntradaLote.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Granja", "Quantidade de Frangos", "Valor de Entrada do Lote ", "Data da Entrada"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneEntradaLote.setViewportView(jTableEntradaLote);

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/editar.png"))); // NOI18N
        jButtonEditar.setText("Editar");

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/excluir.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");

        jLabelIdentificadorLotePesquisa.setText("Identificador do Lote");

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/utfpr/icones/pesquisar.png"))); // NOI18N
        jButtonPesquisar.setText("Perquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLotesAlojadosAba2Layout = new javax.swing.GroupLayout(jPanelLotesAlojadosAba2);
        jPanelLotesAlojadosAba2.setLayout(jPanelLotesAlojadosAba2Layout);
        jPanelLotesAlojadosAba2Layout.setHorizontalGroup(
            jPanelLotesAlojadosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLotesAlojadosAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLotesAlojadosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneEntradaLote, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLotesAlojadosAba2Layout.createSequentialGroup()
                        .addComponent(jLabelIdentificadorLotePesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldIdentificadorLotePesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPesquisar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLotesAlojadosAba2Layout.createSequentialGroup()
                        .addGap(0, 149, Short.MAX_VALUE)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonFecharAba2)))
                .addContainerGap())
        );
        jPanelLotesAlojadosAba2Layout.setVerticalGroup(
            jPanelLotesAlojadosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLotesAlojadosAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLotesAlojadosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelIdentificadorLotePesquisa)
                    .addComponent(jTextFieldIdentificadorLotePesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEntradaLote, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelLotesAlojadosAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonFecharAba2))
                .addContainerGap())
        );

        jTabbedPaneEntradaLotes.addTab("Lotes Alojados", jPanelLotesAlojadosAba2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneEntradaLotes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneEntradaLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonFecharAba1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAba1ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButtonFecharAba1ActionPerformed

    private void jButtonFecharAba2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharAba2ActionPerformed
        super.dispose();
    }//GEN-LAST:event_jButtonFecharAba2ActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if (validaCampos()) {
            EntradaLotes entradaLotes = new EntradaLotes(
                jTextFieldIdentificador.getText(),
                codigosGranjas[jComboBoxGranjas.getSelectedIndex()-1],
                jComboBoxGranjas.getSelectedItem().toString(),
                Integer.parseInt(jFormattedTextFieldQuantidadeFrangos.getText().toString().replace(".", "")),
                Float.parseFloat(jFormattedTextFieldValorEntrada.getText().toString().replace(".", "").replace(",", ".")),
                jFormattedTextFieldDataEntrada.getText().toString()
            );
            
            entradaLotesDao.inserir(entradaLotes);
            
            // Listagem na tabela
            List<EntradaLotes> lista = entradaLotesDao.listar();
            entradaLotesListModel = new EntradaDeLotesListModel(lista);
            jTableEntradaLote.setModel(entradaLotesListModel);

            limpaCampos();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void alimentaComboBoxGranjas() {
        
        List<Granjas> listaGranjas = granjasDao.listar();
        granjasListModel = new GranjasListModel(listaGranjas);
        
        // Cria um array com os itens para a ComboBox
        String[] nomesGranjas = new String[granjasListModel.getRowCount()+1];
        
        codigosGranjas = new Integer[granjasListModel.getRowCount()];
        quantidadesFrangosGranjas = new Integer[granjasListModel.getRowCount()];
        
        for (int i=0; i<=granjasListModel.getRowCount(); i++) {
            if (i==0) {
                nomesGranjas[i] = "Selecione a Granja";
            } else {
                nomesGranjas[i] = granjasListModel.getValueAt(i-1, 1).toString();
                codigosGranjas[i-1] = Integer.parseInt(granjasListModel.getValueAt(i-1, 0).toString());
                quantidadesFrangosGranjas[i-1] = Integer.parseInt(granjasListModel.getValueAt(i-1, 4).toString());
            }
        }
        
        // Cria um modelo de dados para a ComboBox
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(nomesGranjas);

        // Define o modelo de dados
        jComboBoxGranjas.setModel(model);
    }
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // Listagem na tabela
        List<EntradaLotes> lista = entradaLotesDao.buscarPorNome(jTextFieldIdentificadorLotePesquisar.getText());
        entradaLotesListModel = new EntradaDeLotesListModel(lista);
        jTableEntradaLote.setModel(entradaLotesListModel);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void limpaCampos() {
        jTextFieldIdentificador.setText("");
        jComboBoxGranjas.setSelectedIndex(0);
        jFormattedTextFieldQuantidadeFrangos.setText("");
        jFormattedTextFieldValorEntrada.setText("");;
        jFormattedTextFieldDataEntrada.setText("");
    }
    
    private boolean validaCampos() {
        Mensagens mensagens = new Mensagens();
        
        if (jTextFieldIdentificador.getText().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Identificador");
            jTextFieldIdentificador.requestFocus();
            return false;
        } else if (jComboBoxGranjas.getSelectedIndex() == 0) {
            mensagens.errorMessage("Campo Inválido","Selecione uma Granja");
            jComboBoxGranjas.requestFocus();
            return false;
        } else if (jFormattedTextFieldQuantidadeFrangos.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Quantidade de Frangos");
            jFormattedTextFieldQuantidadeFrangos.requestFocus();
            return false;
        } else if (jFormattedTextFieldQuantidadeFrangos.getText().toString().equals("0")) {
            mensagens.errorMessage("Campo Inválido","Preencha uma Quantidade maior que 0");
            jFormattedTextFieldQuantidadeFrangos.requestFocus();
            return false;
        } else if (Integer.parseInt(jFormattedTextFieldQuantidadeFrangos.getText().toString().replace(".", ""))>quantidadesFrangosGranjas[jComboBoxGranjas.getSelectedIndex()-1]) {
            mensagens.errorMessage("Campo Inválido","Capacidade da Granja excedida, preencha uma Quantidade de Frangos menor ou igual a "+quantidadesFrangosGranjas[jComboBoxGranjas.getSelectedIndex()-1].toString()+" frangos");
            jFormattedTextFieldQuantidadeFrangos.requestFocus();
            return false;
        } else if (jFormattedTextFieldValorEntrada.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Valor de Entrada do Lote");
            jFormattedTextFieldValorEntrada.requestFocus();
            return false;
        } else if (jFormattedTextFieldValorEntrada.getText().toString().equals("0,00")) {
            mensagens.errorMessage("Campo Inválido","Preencha um Valor de Entrada do Lote maior que 0");
            jFormattedTextFieldValorEntrada.requestFocus();
            return false;
        } else if (jFormattedTextFieldDataEntrada.getText().toString().isEmpty()) {
            mensagens.errorMessage("Campo Inválido","Preencha o campo Data da Entrada");
            jFormattedTextFieldDataEntrada.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonFecharAba1;
    private javax.swing.JButton jButtonFecharAba2;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxGranjas;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataEntrada;
    private javax.swing.JFormattedTextField jFormattedTextFieldQuantidadeFrangos;
    private javax.swing.JFormattedTextField jFormattedTextFieldValorEntrada;
    private javax.swing.JLabel jLabelDataEntrada;
    private javax.swing.JLabel jLabelGranja;
    private javax.swing.JLabel jLabelIdentificador;
    private javax.swing.JLabel jLabelIdentificadorLotePesquisa;
    private javax.swing.JLabel jLabelQuantidadeFrangos;
    private javax.swing.JLabel jLabelValorEntrada;
    private javax.swing.JPanel jPanelLotesAlojadosAba2;
    private javax.swing.JPanel jPanelRegistrarEntradaLoteAba1;
    private javax.swing.JScrollPane jScrollPaneEntradaLote;
    private javax.swing.JTabbedPane jTabbedPaneEntradaLotes;
    private javax.swing.JTable jTableEntradaLote;
    private javax.swing.JTextField jTextFieldIdentificador;
    private javax.swing.JTextField jTextFieldIdentificadorLotePesquisar;
    // End of variables declaration//GEN-END:variables
}
